### ISSUE TITLE
Sad story

### ISSUE THREAD

**Issue by rkiesler** [frakbot/FWeather#65]
First, I tried running FWeather on my (non-rooted) Nexus S. It was stuck at "Let me look out of a fucking window." for half a week, as noted in the Google Play Store (there, I'm John Doe, as Google already knows way too much about me).

Then, I tried getting logs out of my Nexus S, I hit the Jackpot, I'm on Android 4.1 non-rooted -- no log files without installing the SDK. So I took out my rooted Asus Transformer tablet, running Android 4.0.3.

I installed CatLog, I installed the FWeather widget, and it didn't work. When I drag the FWeather widget to my launch screen, either 

1) I get a popup "Unfortunately, FWeather widget has stopped. [Report | OK]". I click on Report, then I get a popup "Unfortunately, Google Play Store has stopped. [OK]". or
2) Nothing happens.

(I tried it a couple of times)

What's next?

**Comment by rock3r** [comment]
The crash on tablets has been fixed as of v2.1, which is currently in beta. Could you please join the beta (instructions are on the wiki pages of this repo) and try again? 

Thanks!

**Comment by rkiesler** [comment]
Will do. Thanks!

**Comment by rock3r** [comment]
@rkiesler can you confirm the crash is fixed?

**Comment by rkiesler** [comment]
No, I can't confirm that. I joined the Google Plus page, but I don't think I got the update. Looking at Google Play, I only have the option to Uninstall, not to update. And draging the Widget on my screen, it still crashes. Any way of me finding out the currently installed version of FWeather without starting it?

**Comment by rock3r** [comment]
You can find it out in the Apps section of your device's settings. I'm
afraid you didn't actually activate the testing as indicated on the guide:
https://github.com/frakbot/FWeather/wiki/Joining-the-beta

**Comment by rkiesler** [comment]
Yes, you are right, I didn't enable testing. Did so now and will report back how it went.

**Comment by rkiesler** [comment]
Yay, it no longer crashes! I now get "Dafuq, dude! I don't have a fucking crystal ball! Enable the GPS or the Location Services". Tried enabling the location services on the tablet, tried refreshing with the sync update, tried entering my location manually, no change.

**Comment by rock3r** [comment]
I'm wrapping a new beta right now with lots of fixes and a first step in clearer error messages. I hope to get it out today, keep an eye on the G+ community for announcements.

**Comment by rock3r** [comment]
Closed since there has been no further feedback in 19 days.
